//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSZ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ygui_get_f4help_hit_list_webs" +
            "/400/ygui_get_f4help_hit_list/ygui_get_f4help_hit_list_bind")]
        public string SSZ_Hit_List_YGUI_GET_F4HELP_HIT_LIST {
            get {
                return ((string)(this["SSZ_Hit_List_YGUI_GET_F4HELP_HIT_LIST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ygui_get_facade_metadata_webs" +
            "/400/ygui_get_facade_metadata/ygui_get_facade_metadata_bind")]
        public string SSZ_Get_facade_YGUI_GET_FACADE_METADATA {
            get {
                return ((string)(this["SSZ_Get_facade_YGUI_GET_FACADE_METADATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ygui_reuse_grid_variant_webs/" +
            "400/ygui_reuse_grid_variant/ygui_reuse_grid_variant_bind")]
        public string SSZ_ReuseGrid_YGUI_REUSE_GRID_VARIANT {
            get {
                return ((string)(this["SSZ_ReuseGrid_YGUI_REUSE_GRID_VARIANT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ygui_handle_pernr_session_web" +
            "s/400/ygui_handle_pernr_session/ygui_handle_pernr_session_bind")]
        public string SSZ_SessionSap_YGUI_HANDLE_PERNR_SESSION {
            get {
                return ((string)(this["SSZ_SessionSap_YGUI_HANDLE_PERNR_SESSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ysfc_put_operation_ticket_web" +
            "s/400/ysfc_put_operation_ticket/ysfc_put_operation_ticket_bind")]
        public string SSZ_PUT_OPERATION_TICKET_YSFC_PUT_OPERATION_TICKET {
            get {
                return ((string)(this["SSZ_PUT_OPERATION_TICKET_YSFC_PUT_OPERATION_TICKET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ysfc_get_statistics_webs/400/" +
            "ysfc_get_statistics/ysfc_get_statistics_bind")]
        public string SSZ_GetStatistics_YSFC_GET_STATISTICS {
            get {
                return ((string)(this["SSZ_GetStatistics_YSFC_GET_STATISTICS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ysfc_put_notification_webs/40" +
            "0/ysfc_put_notification/ysfc_put_notification_bind")]
        public string SSZ_PutNotification_YSFC_PUT_NOTIFICATION {
            get {
                return ((string)(this["SSZ_PutNotification_YSFC_PUT_NOTIFICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ysfc_get_notif_pro_items_webs" +
            "/400/ysfc_get_notif_pro_items/ysfc_get_notif_pro_items_bind")]
        public string SSZ_GetNotif_YSFC_GET_NOTIF_PRO_ITEMS {
            get {
                return ((string)(this["SSZ_GetNotif_YSFC_GET_NOTIF_PRO_ITEMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ysfc_get_operations_list_webs" +
            "/400/ysfc_get_operations_list/ysfc_get_operations_list_bind")]
        public string SSZ_GetOperService_YSFC_GET_OPERATIONS_LIST {
            get {
                return ((string)(this["SSZ_GetOperService_YSFC_GET_OPERATIONS_LIST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp-dev.sapfir.local:8000/sap/bc/srt/rfc/sap/ysfc_get_operation_detail_web" +
            "s/400/ysfc_get_operation_detail/ysfc_get_operation_detail_bind")]
        public string SSZ_GetOperDetail_YSFC_GET_OPERATION_DETAIL {
            get {
                return ((string)(this["SSZ_GetOperDetail_YSFC_GET_OPERATION_DETAIL"]));
            }
        }
    }
}
