//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSZ.Hit_List {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: Необязательный элемент расширения WSDL "Policy" из пространства имен "http://schemas.xmlsoap.org/ws/2004/09/policy" не был обработан.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="YGUI_GET_F4HELP_HIT_LIST_BIND", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YGUI_GET_F4HELP_HIT_LIST : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback YguiGetF4helpHitListWsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public YGUI_GET_F4HELP_HIT_LIST() {
            this.Url = global::SSZ.Properties.Settings.Default.SSZ_Hit_List_YGUI_GET_F4HELP_HIT_LIST;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event YguiGetF4helpHitListWsCompletedEventHandler YguiGetF4helpHitListWsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:YGUI_GET_F4HELP_HIT_LIST_WEBS:Yg" +
            "uiGetF4helpHitListWsRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("YguiGetF4helpHitListWsResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public YguiGetF4helpHitListWsResponse YguiGetF4helpHitListWs([System.Xml.Serialization.XmlElementAttribute("YguiGetF4helpHitListWs", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] YguiGetF4helpHitListWs YguiGetF4helpHitListWs1) {
            object[] results = this.Invoke("YguiGetF4helpHitListWs", new object[] {
                        YguiGetF4helpHitListWs1});
            return ((YguiGetF4helpHitListWsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void YguiGetF4helpHitListWsAsync(YguiGetF4helpHitListWs YguiGetF4helpHitListWs1) {
            this.YguiGetF4helpHitListWsAsync(YguiGetF4helpHitListWs1, null);
        }
        
        /// <remarks/>
        public void YguiGetF4helpHitListWsAsync(YguiGetF4helpHitListWs YguiGetF4helpHitListWs1, object userState) {
            if ((this.YguiGetF4helpHitListWsOperationCompleted == null)) {
                this.YguiGetF4helpHitListWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYguiGetF4helpHitListWsOperationCompleted);
            }
            this.InvokeAsync("YguiGetF4helpHitListWs", new object[] {
                        YguiGetF4helpHitListWs1}, this.YguiGetF4helpHitListWsOperationCompleted, userState);
        }
        
        private void OnYguiGetF4helpHitListWsOperationCompleted(object arg) {
            if ((this.YguiGetF4helpHitListWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YguiGetF4helpHitListWsCompleted(this, new YguiGetF4helpHitListWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YguiGetF4helpHitListWs {
        
        private string iFieldMappedNameField;
        
        private string iFuncMappedNameField;
        
        private string iIdField;
        
        private string iMaxRowsField;
        
        private string iParamMappedNameField;
        
        private string iSearchContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFieldMappedName {
            get {
                return this.iFieldMappedNameField;
            }
            set {
                this.iFieldMappedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFuncMappedName {
            get {
                return this.iFuncMappedNameField;
            }
            set {
                this.iFuncMappedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IId {
            get {
                return this.iIdField;
            }
            set {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMaxRows {
            get {
                return this.iMaxRowsField;
            }
            set {
                this.iMaxRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IParamMappedName {
            get {
                return this.iParamMappedNameField;
            }
            set {
                this.iParamMappedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISearchContext {
            get {
                return this.iSearchContextField;
            }
            set {
                this.iSearchContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YguiFieldDescWs {
        
        private string typenameField;
        
        private string fieldnameField;
        
        private string inttypeField;
        
        private string intlenField;
        
        private string fieldtextField;
        
        private string reptextField;
        
        private string scrtextSField;
        
        private string scrtextMField;
        
        private string scrtextLField;
        
        private string f4availablField;
        
        private string colPosField;
        
        private string noOutField;
        
        private string outputlenField;
        
        private string fontSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Typename {
            get {
                return this.typenameField;
            }
            set {
                this.typenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fieldname {
            get {
                return this.fieldnameField;
            }
            set {
                this.fieldnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Inttype {
            get {
                return this.inttypeField;
            }
            set {
                this.inttypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Intlen {
            get {
                return this.intlenField;
            }
            set {
                this.intlenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fieldtext {
            get {
                return this.fieldtextField;
            }
            set {
                this.fieldtextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reptext {
            get {
                return this.reptextField;
            }
            set {
                this.reptextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ScrtextS {
            get {
                return this.scrtextSField;
            }
            set {
                this.scrtextSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ScrtextM {
            get {
                return this.scrtextMField;
            }
            set {
                this.scrtextMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ScrtextL {
            get {
                return this.scrtextLField;
            }
            set {
                this.scrtextLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F4availabl {
            get {
                return this.f4availablField;
            }
            set {
                this.f4availablField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ColPos {
            get {
                return this.colPosField;
            }
            set {
                this.colPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoOut {
            get {
                return this.noOutField;
            }
            set {
                this.noOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Outputlen {
            get {
                return this.outputlenField;
            }
            set {
                this.outputlenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YguiGetF4helpHitListWsResponse {
        
        private string eMaxRowsExceededField;
        
        private YguiFieldDescWs[] etHitListDescWsField;
        
        private string[] etHitListWsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMaxRowsExceeded {
            get {
                return this.eMaxRowsExceededField;
            }
            set {
                this.eMaxRowsExceededField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public YguiFieldDescWs[] EtHitListDescWs {
            get {
                return this.etHitListDescWsField;
            }
            set {
                this.etHitListDescWsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] EtHitListWs {
            get {
                return this.etHitListWsField;
            }
            set {
                this.etHitListWsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void YguiGetF4helpHitListWsCompletedEventHandler(object sender, YguiGetF4helpHitListWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YguiGetF4helpHitListWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YguiGetF4helpHitListWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YguiGetF4helpHitListWsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YguiGetF4helpHitListWsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591