//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSZ.SessionSap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: Необязательный элемент расширения WSDL "Policy" из пространства имен "http://schemas.xmlsoap.org/ws/2004/09/policy" не был обработан.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="YGUI_HANDLE_PERNR_SESSION_BIND", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YGUI_HANDLE_PERNR_SESSION : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback YguiHandlePernrSessionWsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public YGUI_HANDLE_PERNR_SESSION() {
            this.Url = global::SSZ.Properties.Settings.Default.SSZ_SessionSap_YGUI_HANDLE_PERNR_SESSION;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event YguiHandlePernrSessionWsCompletedEventHandler YguiHandlePernrSessionWsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:YGUI_HANDLE_PERNR_SESSION_WEBS:Y" +
            "guiHandlePernrSessionWsRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("YguiHandlePernrSessionWsResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public YguiHandlePernrSessionWsResponse YguiHandlePernrSessionWs([System.Xml.Serialization.XmlElementAttribute("YguiHandlePernrSessionWs", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] YguiHandlePernrSessionWs YguiHandlePernrSessionWs1) {
            object[] results = this.Invoke("YguiHandlePernrSessionWs", new object[] {
                        YguiHandlePernrSessionWs1});
            return ((YguiHandlePernrSessionWsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void YguiHandlePernrSessionWsAsync(YguiHandlePernrSessionWs YguiHandlePernrSessionWs1) {
            this.YguiHandlePernrSessionWsAsync(YguiHandlePernrSessionWs1, null);
        }
        
        /// <remarks/>
        public void YguiHandlePernrSessionWsAsync(YguiHandlePernrSessionWs YguiHandlePernrSessionWs1, object userState) {
            if ((this.YguiHandlePernrSessionWsOperationCompleted == null)) {
                this.YguiHandlePernrSessionWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYguiHandlePernrSessionWsOperationCompleted);
            }
            this.InvokeAsync("YguiHandlePernrSessionWs", new object[] {
                        YguiHandlePernrSessionWs1}, this.YguiHandlePernrSessionWsOperationCompleted, userState);
        }
        
        private void OnYguiHandlePernrSessionWsOperationCompleted(object arg) {
            if ((this.YguiHandlePernrSessionWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YguiHandlePernrSessionWsCompleted(this, new YguiHandlePernrSessionWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YguiHandlePernrSessionWs {
        
        private string iActionField;
        
        private string iApplField;
        
        private string iAttemptsField;
        
        private string iIdField;
        
        private string iLanguField;
        
        private string iModeField;
        
        private string iPernrField;
        
        private string iPlantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IAction {
            get {
                return this.iActionField;
            }
            set {
                this.iActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IAppl {
            get {
                return this.iApplField;
            }
            set {
                this.iApplField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IAttempts {
            get {
                return this.iAttemptsField;
            }
            set {
                this.iAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IId {
            get {
                return this.iIdField;
            }
            set {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ILangu {
            get {
                return this.iLanguField;
            }
            set {
                this.iLanguField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMode {
            get {
                return this.iModeField;
            }
            set {
                this.iModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IPernr {
            get {
                return this.iPernrField;
            }
            set {
                this.iPernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IPlant {
            get {
                return this.iPlantField;
            }
            set {
                this.iPlantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YguiHandlePernrSessionWsResponse {
        
        private string eApplField;
        
        private string eIdField;
        
        private string ePernrField;
        
        private string ePlantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EAppl {
            get {
                return this.eApplField;
            }
            set {
                this.eApplField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EId {
            get {
                return this.eIdField;
            }
            set {
                this.eIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EPernr {
            get {
                return this.ePernrField;
            }
            set {
                this.ePernrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EPlant {
            get {
                return this.ePlantField;
            }
            set {
                this.ePlantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void YguiHandlePernrSessionWsCompletedEventHandler(object sender, YguiHandlePernrSessionWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YguiHandlePernrSessionWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YguiHandlePernrSessionWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YguiHandlePernrSessionWsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YguiHandlePernrSessionWsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591